easy_admin:
    site_name: 'My Admin'
    design:
        menu: [{ entity: 'Provider', label: 'Data Providers' },
               { entity: 'Product', label: 'Credit Cards' }]
    formats:
        date: 'd/m/Y'
    entities:
        Provider:
            class: App\Entity\Provider
            controller: App\Controller\Admin\AdminProviderController
            label: Data Providers
            list:
                sort: ['id', 'DESC']
                disabled_actions: ['delete']
                actions:                                                               
                    - { name: 'editProvider', type: 'route', label: 'Edit' }  
                fields:
                    - { property: 'name', label: 'Name' }
                    - { property: 'affiliation', label: 'Type' }
            form:
                fields:
                    - { property: 'name',type_options: { required: true } }
                    - { property: 'affiliation', label: 'Type', type: 'choice', type_options: {choices: { 'Affiliate': 'affiliate', 'Direct': 'direct' }}}
                    - { property: 'ws_url', type: 'text',type_options: { required: true } }
                    - { property: 'ws_url_stats', type: 'text',type_options: { required: true } }
                    - { property: 'data_type', type: 'text',type_options: { required: true } }
                    - { property: 'api_user', type: 'text'}
                    - { property: 'api_key', type: 'text',type_options: { required: true } }
                    - { property: 'slug', type: 'text'}
        Product:
            class: App\Entity\Product
            controller: App\Controller\Admin\AdminProductController
            label: Credit Cards
            disabled_actions: ['delete']
            form:
                fields:
                    - { property: 'name'}
                    - { property: 'provider', label: 'Data provider'}
                    - { property: 'link', label: 'Deep link', type: 'text',type_options: { required: true } }
                    - { property: 'final_url', type: 'text',type_options: { required: true } }
                    - { property: 'provider_reference', type: 'hidden',type_options: { data: '0' } }
                    - { property: 'visible', type: 'hidden',type_options: { data: '0' } }
            list:
                actions:
                    - { name: 'edit', label: '' }
                fields:
                    - { property: 'name', label: 'Name' }
                    - { property: 'Provider.name', label: 'Data provider' }
                    - { property: 'visible', label: 'Visible in Web', type: 'toggle' }